---
name: docker-build

permissions:
  packages: write

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAGS: "latest"
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository.
        uses: actions/checkout@v4

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        id: build_image
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: Dockerfile

      - name: Push Image to GHCR.
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
